import { writeFileSync } from 'fs';
import type { Publisher, ReleaseNotes, OutputFormat } from '../types';
import { formatNotes } from '../formatter';
import { fetchWithTimeout } from '../fetch';

/**
 * Outputs release notes to stdout (default).
 */
export class StdoutPublisher implements Publisher {
  async publish(notes: ReleaseNotes, format: OutputFormat): Promise<void> {
    const formatted = formatNotes(notes, format);
    console.log(formatted);
  }
}

/**
 * Writes release notes to a file.
 */
export class FilePublisher implements Publisher {
  constructor(private path: string) {}

  async publish(notes: ReleaseNotes, format: OutputFormat): Promise<void> {
    const formatted = formatNotes(notes, format);
    writeFileSync(this.path, formatted, 'utf-8');
    console.log(`✓ Release notes written to ${this.path}`);
  }
}

/**
 * Posts release notes to a Slack channel via webhook.
 */
export class SlackPublisher implements Publisher {
  constructor(private webhookUrl: string) {
    if (!webhookUrl.startsWith('https://hooks.slack.com/') && !webhookUrl.startsWith('https://hooks.slack-gov.com/')) {
      throw new Error('Invalid Slack webhook URL — must start with https://hooks.slack.com/ or https://hooks.slack-gov.com/');
    }
  }

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const text = this.buildSlackMessage(notes);

    const response = await fetchWithTimeout(this.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text }),
    });

    if (!response.ok) {
      throw new Error(`Slack webhook failed (${response.status})`);
    }
    console.log('✓ Published to Slack');
  }

  private buildSlackMessage(notes: ReleaseNotes): string {
    let msg = `*${notes.version}* — ${notes.date}\n`;
    if (notes.summary) msg += `${notes.summary}\n\n`;

    const categoryEmoji: Record<string, string> = {
      features: '✨', fixes: '🐛', breaking: '⚠️',
      improvements: '🔧', chores: '🧹', other: '📝'
    };

    for (const change of notes.changes) {
      const emoji = categoryEmoji[change.category] || '•';
      msg += `${emoji} ${change.description}`;
      if (change.ticketKey) msg += ` (\`${change.ticketKey}\`)`;
      msg += '\n';
    }

    return msg;
  }
}

/**
 * Posts release notes to Discord via webhook.
 */
export class DiscordPublisher implements Publisher {
  constructor(private webhookUrl: string) {
    if (!webhookUrl.startsWith('https://discord.com/api/webhooks/') && !webhookUrl.startsWith('https://discordapp.com/api/webhooks/')) {
      throw new Error('Invalid Discord webhook URL — must start with https://discord.com/api/webhooks/');
    }
  }

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const content = this.buildDiscordMessage(notes);

    const response = await fetchWithTimeout(this.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        embeds: [{
          title: `Release ${notes.version}`,
          description: content,
          color: 0xe8ff47, // Cullit accent color
          timestamp: new Date().toISOString(),
          footer: { text: 'Generated by Cullit' },
        }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Discord webhook failed (${response.status})`);
    }
    console.log('✓ Published to Discord');
  }

  private buildDiscordMessage(notes: ReleaseNotes): string {
    let msg = '';
    if (notes.summary) msg += `${notes.summary}\n\n`;

    for (const change of notes.changes) {
      msg += `• ${change.description}`;
      if (change.ticketKey) msg += ` (${change.ticketKey})`;
      msg += '\n';
    }

    return msg.substring(0, 4000); // Discord embed limit
  }
}

/**
 * Creates or updates a GitHub Release via the GitHub API.
 * Requires GITHUB_TOKEN env var (provided automatically in GitHub Actions).
 */
export class GitHubReleasePublisher implements Publisher {
  private token: string;
  private owner: string;
  private repo: string;

  constructor() {
    this.token = process.env['GITHUB_TOKEN'] || '';
    // GITHUB_REPOSITORY is "owner/repo" in Actions
    const ghRepo = process.env['GITHUB_REPOSITORY'] || '';
    const parts = ghRepo.split('/');
    this.owner = parts[0] || '';
    this.repo = parts[1] || '';
  }

  async publish(notes: ReleaseNotes, format: OutputFormat): Promise<void> {
    if (!this.token) {
      throw new Error('GITHUB_TOKEN is required for GitHub Release publishing');
    }
    if (!this.owner || !this.repo) {
      throw new Error(
        'GITHUB_REPOSITORY env var is required (format: owner/repo). ' +
        'This is set automatically in GitHub Actions.'
      );
    }

    const formatted = formatNotes(notes, format);
    const tagName = notes.version.startsWith('v') ? notes.version : `v${notes.version}`;

    // Check if release already exists for this tag
    const existing = await this.getRelease(tagName);

    if (existing) {
      await this.updateRelease(existing.id, formatted, notes);
      console.log(`✓ Updated GitHub Release: ${tagName}`);
    } else {
      await this.createRelease(tagName, formatted, notes);
      console.log(`✓ Created GitHub Release: ${tagName}`);
    }
  }

  private async getRelease(tag: string): Promise<{ id: number } | null> {
    const url = `https://api.github.com/repos/${this.owner}/${this.repo}/releases/tags/${encodeURIComponent(tag)}`;
    const response = await fetchWithTimeout(url, {
      headers: this.headers(),
    });

    if (response.status === 404) return null;
    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub API error (${response.status}): ${error}`);
    }

    const data = await response.json() as { id: number };
    return data;
  }

  private async createRelease(tag: string, body: string, notes: ReleaseNotes): Promise<void> {
    const url = `https://api.github.com/repos/${this.owner}/${this.repo}/releases`;
    const response = await fetchWithTimeout(url, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify({
        tag_name: tag,
        name: `${tag} — ${notes.date}`,
        body,
        draft: false,
        prerelease: tag.includes('-'),
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub Release creation failed (${response.status}): ${error}`);
    }
  }

  private async updateRelease(id: number, body: string, notes: ReleaseNotes): Promise<void> {
    const tag = notes.version.startsWith('v') ? notes.version : `v${notes.version}`;
    const url = `https://api.github.com/repos/${this.owner}/${this.repo}/releases/${id}`;
    const response = await fetchWithTimeout(url, {
      method: 'PATCH',
      headers: this.headers(),
      body: JSON.stringify({
        body,
        name: `${tag} — ${notes.date}`,
      }),
    });

    if (!response.ok) {
      const error = await response.text();
      throw new Error(`GitHub Release update failed (${response.status}): ${error}`);
    }
  }

  private headers(): Record<string, string> {
    return {
      'Accept': 'application/vnd.github+json',
      'Authorization': `Bearer ${this.token}`,
      'X-GitHub-Api-Version': '2022-11-28',
    };
  }
}
