import { writeFileSync } from 'fs';
import type { Publisher, ReleaseNotes, OutputFormat } from '../types';
import { formatNotes } from '../formatter';

/**
 * Outputs release notes to stdout (default).
 */
export class StdoutPublisher implements Publisher {
  async publish(notes: ReleaseNotes, format: OutputFormat): Promise<void> {
    const formatted = formatNotes(notes, format);
    console.log(formatted);
  }
}

/**
 * Writes release notes to a file.
 */
export class FilePublisher implements Publisher {
  constructor(private path: string) {}

  async publish(notes: ReleaseNotes, format: OutputFormat): Promise<void> {
    const formatted = formatNotes(notes, format);
    writeFileSync(this.path, formatted, 'utf-8');
    console.log(`✓ Release notes written to ${this.path}`);
  }
}

/**
 * Posts release notes to a Slack channel via webhook.
 */
export class SlackPublisher implements Publisher {
  constructor(private webhookUrl: string) {}

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const text = this.buildSlackMessage(notes);

    const response = await fetch(this.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text }),
    });

    if (!response.ok) {
      throw new Error(`Slack webhook failed (${response.status})`);
    }
    console.log('✓ Published to Slack');
  }

  private buildSlackMessage(notes: ReleaseNotes): string {
    let msg = `*${notes.version}* — ${notes.date}\n`;
    if (notes.summary) msg += `${notes.summary}\n\n`;

    const categoryEmoji: Record<string, string> = {
      features: '✨', fixes: '🐛', breaking: '⚠️',
      improvements: '🔧', chores: '🧹', other: '📝'
    };

    for (const change of notes.changes) {
      const emoji = categoryEmoji[change.category] || '•';
      msg += `${emoji} ${change.description}`;
      if (change.ticketKey) msg += ` (\`${change.ticketKey}\`)`;
      msg += '\n';
    }

    return msg;
  }
}

/**
 * Posts release notes to Discord via webhook.
 */
export class DiscordPublisher implements Publisher {
  constructor(private webhookUrl: string) {}

  async publish(notes: ReleaseNotes, _format: OutputFormat): Promise<void> {
    const content = this.buildDiscordMessage(notes);

    const response = await fetch(this.webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        embeds: [{
          title: `Release ${notes.version}`,
          description: content,
          color: 0xe8ff47, // Cull accent color
          timestamp: new Date().toISOString(),
          footer: { text: 'Generated by Cull' },
        }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Discord webhook failed (${response.status})`);
    }
    console.log('✓ Published to Discord');
  }

  private buildDiscordMessage(notes: ReleaseNotes): string {
    let msg = '';
    if (notes.summary) msg += `${notes.summary}\n\n`;

    for (const change of notes.changes) {
      msg += `• ${change.description}`;
      if (change.ticketKey) msg += ` (${change.ticketKey})`;
      msg += '\n';
    }

    return msg.substring(0, 4000); // Discord embed limit
  }
}
