import type { ReleaseNotes, OutputFormat, ChangeCategory } from './types';

const CATEGORY_LABELS: Record<ChangeCategory, string> = {
  features: '✨ Features',
  fixes: '🐛 Bug Fixes',
  breaking: '⚠️ Breaking Changes',
  improvements: '🔧 Improvements',
  chores: '🧹 Chores',
  other: '📝 Other',
};

const CATEGORY_ORDER: ChangeCategory[] = [
  'breaking', 'features', 'improvements', 'fixes', 'chores', 'other'
];

export function formatNotes(notes: ReleaseNotes, format: OutputFormat): string {
  switch (format) {
    case 'markdown': return formatMarkdown(notes);
    case 'html': return formatHTML(notes);
    case 'json': return JSON.stringify(notes, null, 2);
    default: return formatMarkdown(notes);
  }
}

function formatMarkdown(notes: ReleaseNotes): string {
  const lines: string[] = [];

  lines.push(`## ${notes.version} — ${notes.date}`);
  lines.push('');

  if (notes.summary) {
    lines.push(notes.summary);
    lines.push('');
  }

  // Group changes by category
  const grouped = groupByCategory(notes);

  for (const category of CATEGORY_ORDER) {
    const entries = grouped.get(category);
    if (!entries?.length) continue;

    lines.push(`### ${CATEGORY_LABELS[category]}`);
    lines.push('');

    for (const entry of entries) {
      let line = `- ${entry.description}`;
      if (entry.ticketKey) line += ` (${entry.ticketKey})`;
      lines.push(line);
    }
    lines.push('');
  }

  if (notes.contributors?.length) {
    lines.push('### Contributors');
    lines.push('');
    lines.push(notes.contributors.map(c => `@${c}`).join(', '));
    lines.push('');
  }

  if (notes.metadata) {
    lines.push('---');
    lines.push(`*Generated by [Cull](https://cullit.io) • ${notes.metadata.commitCount} commits, ${notes.metadata.prCount} PRs*`);
  }

  return lines.join('\n');
}

function formatHTML(notes: ReleaseNotes): string {
  const grouped = groupByCategory(notes);
  let html = `<div class="cull-release">`;
  html += `<h2>${notes.version} — ${notes.date}</h2>`;

  if (notes.summary) {
    html += `<p class="summary">${notes.summary}</p>`;
  }

  for (const category of CATEGORY_ORDER) {
    const entries = grouped.get(category);
    if (!entries?.length) continue;

    html += `<h3>${CATEGORY_LABELS[category]}</h3><ul>`;
    for (const entry of entries) {
      html += `<li>${entry.description}`;
      if (entry.ticketKey) html += ` <code>${entry.ticketKey}</code>`;
      html += `</li>`;
    }
    html += `</ul>`;
  }

  html += `</div>`;
  return html;
}

function groupByCategory(notes: ReleaseNotes) {
  const grouped = new Map<ChangeCategory, typeof notes.changes>();
  for (const entry of notes.changes) {
    const existing = grouped.get(entry.category) || [];
    existing.push(entry);
    grouped.set(entry.category, existing);
  }
  return grouped;
}
