import type { ReleaseNotes, OutputFormat, ChangeCategory } from './types';

// --- Formatter Registry ---

type FormatterFn = (notes: ReleaseNotes) => string;
const formatters = new Map<string, FormatterFn>();

export function registerFormatter(format: string, fn: FormatterFn): void {
  formatters.set(format, fn);
}

export function getFormatter(format: string): FormatterFn | undefined {
  return formatters.get(format);
}

export function listFormatters(): string[] {
  return Array.from(formatters.keys());
}

const CATEGORY_LABELS: Record<string, string> = {
  features: '✨ Features',
  fixes: '🐛 Bug Fixes',
  breaking: '⚠️ Breaking Changes',
  improvements: '🔧 Improvements',
  chores: '🧹 Chores',
  other: '📝 Other',
};

const CATEGORY_ORDER: ChangeCategory[] = [
  'breaking', 'features', 'improvements', 'fixes', 'chores', 'other'
];

export function formatNotes(notes: ReleaseNotes, format: OutputFormat): string {
  const fn = formatters.get(format) || formatters.get('markdown')!;
  return fn(notes);
}

function formatMarkdown(notes: ReleaseNotes): string {
  const lines: string[] = [];

  lines.push(`## ${notes.version} — ${notes.date}`);
  lines.push('');

  if (notes.summary) {
    lines.push(notes.summary);
    lines.push('');
  }

  // Group changes by category
  const grouped = groupByCategory(notes);

  for (const category of CATEGORY_ORDER) {
    const entries = grouped.get(category);
    if (!entries?.length) continue;

    lines.push(`### ${CATEGORY_LABELS[category]}`);
    lines.push('');

    for (const entry of entries) {
      let line = `- ${entry.description}`;
      if (entry.ticketKey) line += ` (${entry.ticketKey})`;
      lines.push(line);
    }
    lines.push('');
  }

  if (notes.contributors?.length) {
    lines.push('### Contributors');
    lines.push('');
    lines.push(notes.contributors.map(c => `@${c}`).join(', '));
    lines.push('');
  }

  if (notes.metadata) {
    lines.push('---');
    lines.push(`*Generated by [Cullit](https://cullit.io) • ${notes.metadata.commitCount} commits, ${notes.metadata.prCount} PRs*`);
  }

  return lines.join('\n');
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatHTML(notes: ReleaseNotes): string {
  const grouped = groupByCategory(notes);
  let html = `<div class="cull-release">`;
  html += `<h2>${escapeHtml(notes.version)} — ${escapeHtml(notes.date)}</h2>`;

  if (notes.summary) {
    html += `<p class="summary">${escapeHtml(notes.summary)}</p>`;
  }

  for (const category of CATEGORY_ORDER) {
    const entries = grouped.get(category);
    if (!entries?.length) continue;

    html += `<h3>${CATEGORY_LABELS[category]}</h3><ul>`;
    for (const entry of entries) {
      html += `<li>${escapeHtml(entry.description)}`;
      if (entry.ticketKey) html += ` <code>${escapeHtml(entry.ticketKey)}</code>`;
      html += `</li>`;
    }
    html += `</ul>`;
  }

  if (notes.metadata) {
    html += `<footer><small>Generated by <a href="https://cullit.io">Cullit</a> &bull; ${notes.metadata.commitCount} commits, ${notes.metadata.prCount} PRs</small></footer>`;
  }

  html += `</div>`;
  return html;
}

function groupByCategory(notes: ReleaseNotes) {
  const grouped = new Map<ChangeCategory, typeof notes.changes>();
  for (const entry of notes.changes) {
    const existing = grouped.get(entry.category) || [];
    existing.push(entry);
    grouped.set(entry.category, existing);
  }
  return grouped;
}

// --- Register built-in formatters ---
registerFormatter('markdown', formatMarkdown);
registerFormatter('html', formatHTML);
registerFormatter('json', (notes) => JSON.stringify(notes, null, 2));
